import { useEffect } from "react"
import Head from 'next/head'
import { useRouter } from "next/router"

export default function Home() {
  const router = useRouter()

  useEffect(() => {
    router.replace("/home")
  })

  return (
    <div >
      <Head>
        <title>Wavelabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    

    </div>
  )
}
